config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  post '/callback', to: 'line_webhook#callback'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get '/notifications', to: 'notifications#index', as: 'user_notifications'
  resources :users
  resources :events do
    get 'calendar', on: :collection
    resources :reservations, only: %i[new create destroy]
  end
  resources :bulletins do
    member do
      post 'like'
      delete 'unlike'
    end
  end
  resources :notifications, only: [:index] do
    member do
      put :mark_as_read
    end
  end
  resources :chat_messages, only: %i[index create]
  resources :bulletin_chats, only: %i[index create]
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
  has_one_attached :image
  has_many :bulletin_chats, dependent: :destroy
end

app/controllers/bulletins_controller.rb
# frozen_string_literal: true

class BulletinsController < ApplicationController
  before_action :set_bulletin, only: %i[show edit update destroy]

  def index
    @selected_attribute = params[:attribute_id]
    @attributes = %w[テクニカル分析 ファンダメンタル分析 その他]
    @bulletins = if @selected_attribute.present? && @selected_attribute != 'すべて'
                   Bulletin.where(new_attributes: @selected_attribute)
                 else
                   Bulletin.all
                 end
  end

  def show; end

  def new
    @bulletin = Bulletin.new
  end

  def create
    @bulletin = current_user.bulletins.build(bulletin_params)

    if @bulletin.save
      redirect_to @bulletin, notice: '掲示が作成されました。'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @bulletin.update(bulletin_params)
      redirect_to @bulletin, notice: '掲示が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @bulletin.destroy
    redirect_to bulletins_url, notice: '掲示が削除されました。'
  end

  def like
    @bulletin = Bulletin.find(params[:id])

    if current_user.liked_bulletins.include?(@bulletin)
      remove_like
    else
      create_like
    end

    render_likes_count
  end

  private

  def remove_like
    @bulletin.likes.find_by(user_id: current_user.id).destroy
  end

  def create_like
    current_user.likes.create(bulletin: @bulletin)
  end

  def render_likes_count
    new_like_count = @bulletin.likes.count
    respond_to do |format|
      format.json { render json: { likes_count: new_like_count } }
    end
  end

  def unlike
    @bulletin = Bulletin.find(params[:id])

    like = current_user.likes.find_by(bulletin: @bulletin)

    like&.destroy

    new_like_count = @bulletin.likes.count

    respond_to do |format|
      format.json { render json: { likes_count: new_like_count } }
    end
  end

  def set_bulletin
    @bulletin = Bulletin.find(params[:id])
  end

  def bulletin_params
    params.require(:bulletin).permit(:title, :content, :new_attributes, :image)
  end
end

app/views/bulletins/edit.html.erb
<div class="container">
  <h1 class="page-title">掲示を編集</h1>

  <%= form_with model: @bulletin, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :content, "内容" %>
      <%= f.text_area :content, class: "form-control" %>
    </div>

    <!-- 他の掲示内容のフォームを追加 -->

    <div class="actions">
      <%= f.submit "更新", class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to "詳細に戻る", @bulletin, class: "btn btn-secondary" %>
</div>

app/views/bulletins/index.html.erb
<div class="container3">
  <h1 class="page-title">掲示板一覧</h1>

  <div class="filter-section">
  <%= form_tag(bulletins_path, method: "get") do %>
  <label for="attribute-filter">属性を選択:</label>
  <select id="attribute-filter" name="attribute_id">
    <option value="">すべて</option>
    <% @attributes.each do |attribute| %>
      <option value="<%= attribute %>" <%= 'selected' if attribute == @selected_attribute %>>
        <%= attribute %>
      </option>
    <% end %>
  </select>
  <%= submit_tag("フィルタ") %>
  <% end %>
 </div>


  <ul class="bulletin-list">
    <% @bulletins.each do |bulletin| %>
      <li class="bulletin-item">
        <h2 class="bulletin-title"><%= bulletin.title %></h2>
        <p class="bulletin-content">内容: <%= bulletin.content %></p>
          
        <% if bulletin.image.attached? %>
        
          <!-- 画像の表示 -->
          <%= image_tag bulletin.image, class: "bulletin-image" %>
        <% else %>
          <!-- 画像が添付されていない場合の表示 -->
        <% end %>

        <!-- 属性の表示 -->
        <% if bulletin.new_attributes.present? %>
          <p class="bulletin-attributes">属性: <%= bulletin.new_attributes %></p>
        <% end %>

        <div class="like-section">
          <!-- いいねボタン -->
          <button class="like-button <%= current_user && current_user.liked_bulletins.include?(bulletin) ? 'liked' : '' %>" data-bulletin-id="<%= bulletin.id %>" onclick="likeBulletin(<%= bulletin.id %>)">
            <i class="fas fa-thumbs-up"></i> いいね
          </button>
          <span class="like-count" id="like-count-<%= bulletin.id %>">
            <%= bulletin.likes.count %> いいね
          </span>
        </div>
        <%= link_to "詳細を見る", bulletin_path(bulletin), data: { turbolinks: false } %> 
        <% if bulletin.user == current_user %>
  <%= link_to '削除', bulletin_path(bulletin), method: :delete, data: { confirm: '本当に削除しますか？' } %>
<% end %>
      </li>
    <% end %>
  </ul>
  
  <%= link_to "新規投稿", new_bulletin_path, class: "btn btn-primary" %>
</div>

app/views/bulletins/new.html.erb
<div class="container5">
  <section class="user-registration">
  <h1>新規掲示を投稿</h1>
 
  <%= form_with model: @bulletin, local: true do |f| %>
    <div class="form-content">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>


   
      <%= f.label :content, "内容" %>
      <%= f.text_area :content, rows: 4 %>
   

    
      <%= f.label :new_attributes, "属性" %>
      <%= f.select :new_attributes, ["テクニカル分析", "ファンダメンタル分析", "その他"], {} %>



      <%= f.label :image, "画像" %>
      <%= f.file_field :image %>

    <div class="actions">
      <%= f.submit "投稿", class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to "一覧に戻る", bulletins_path %>
  </section>
</div>

app/views/bulletins/show.html.erb
<div class="container6">
  <h1 class="page-title">掲示板詳細</h1>
  <ul class="bulletin-list">
    <li class="bulletin-item">
      <h2 class="bulletin-title"><%= @bulletin.title %></h2>
      <p class="bulletin-content">内容: <%= @bulletin.content %></p>

      <% if @bulletin.image.attached? %>
       
        <%= image_tag @bulletin.image, class: "bulletin-image" %>
      <% else %>
        
      <% end %>

      <!-- 属性の表示 -->
      <% if @bulletin.new_attributes.present? %>
        <p class="bulletin-attributes">属性: <%= @bulletin.new_attributes %></p>
      <% end %>

      <div class="like-section">
        
        <button class="like-button <%= current_user && current_user.liked_bulletins.include?(@bulletin) ? 'liked' : '' %>" data-bulletin-id="<%= @bulletin.id %>" onclick="likeBulletin(<%= @bulletin.id %>)">
          <i class="fas fa-thumbs-up"></i> いいね
        </button>
        <span class="like-count" id="like-count-<%= @bulletin.id %>">
          <%= @bulletin.likes.count %> いいね
        </span>
      </div>

      <% if @bulletin.user == current_user %>
        <%= link_to '削除', bulletin_path(@bulletin), method: :delete, data: { confirm: '本当に削除しますか？' } %>
      <% end %>
    </li>
  </ul>
</div>

<div id="chat" class="chat-container">
  <h2 class="chat-heading">チャット</h2>
  <div id="chat-messages" class="chat-messages">
    
  </div>
</div>

<div class="chat-input-container">
  <input type="text" id="chat-input" class="chat-input" placeholder="チャットを入力...">
  <button id="chat-send" class="chat-send">送信</button>
</div>
</div>




<script>
document.addEventListener('DOMContentLoaded', function() {
    var user_id = '<%= current_user.id %>';
    var user_name = '<%= current_user.nickname %>';
    var chatChannel;

    function createBulletinChatChannel(bulletinId) {
      chatChannel = App.cable.subscriptions.create(
        {
          channel: "BulletinChatChannel",
          bulletin_id: bulletinId,
          user_id: user_id,
          user_name: user_name,
        },
        {
          received: function(data) {
            
            var chatMessages = document.getElementById('chat-messages');
            var messageElement = document.createElement('div');
            messageElement.className = 'chat-message';

            var userIcon = document.createElement('i');
            userIcon.className = 'fas fa-user'; 

            var userName = document.createElement('p');
            userName.className = 'user-name';
            userName.innerText = data.user_name;

            var messageContent = document.createElement('p');
            messageContent.className = 'message-content';
            messageContent.innerText = data.content;

            messageElement.appendChild(userIcon);
            messageElement.appendChild(userName);
            messageElement.appendChild(messageContent);

            chatMessages.appendChild(messageElement);
          }
        }
      );
    }

   
    var bulletinId = '<%= @bulletin.id %>';

    loadChatMessageHistory(bulletinId);
    createBulletinChatChannel(bulletinId);

    function loadChatMessageHistory(bulletinId) {
      
      $.ajax({
        url: '/bulletin_chats',
        method: 'GET',
        data: { bulletin_id: bulletinId },
        dataType: 'json',
        success: function(data) {
          var chatMessages = document.getElementById('chat-messages');
          data.forEach(function(message) {
            var messageElement = document.createElement('div');
            messageElement.className = 'chat-message';

            var userIcon = document.createElement('i');
            userIcon.className = 'fas fa-user';

            var userName = document.createElement('p');
            userName.className = 'user-name';
            userName.innerText = message.user_name; 

            var messageContent = document.createElement('p');
            messageContent.className = 'message-content';
            messageContent.innerText = message.content;

            messageElement.appendChild(userIcon);
            messageElement.appendChild(userName);
            messageElement.appendChild(messageContent);

            chatMessages.appendChild(messageElement);
          });
        }
      });
    }

    document.getElementById('chat-send').addEventListener('click', function() {
      var input = document.getElementById('chat-input');
      var message = input.value;
      if (message.trim() !== '') {
        chatChannel.perform('speak', { content: message, user_name: user_name });
        input.value = '';
      }
    });
  });
</script>