config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  post '/callback', to: 'line_webhook#callback'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get '/notifications', to: 'notifications#index', as: 'user_notifications'
  resources :users
  resources :events do
    get 'calendar', on: :collection
    resources :reservations, only: %i[new create destroy]
  end
  resources :bulletins do
    member do
      post 'like'
      delete 'unlike'
    end
  end
  resources :notifications, only: [:index] do
    member do
      put :mark_as_read
    end
  end
  resources :chat_messages, only: %i[index create]
  resources :bulletin_chats, only: %i[index create]
end

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<header>
<a class="logo" href="<%= root_path %>">FXTradeHub</a>
  <nav>
    <ul>
      <% if current_user %>
      
        <li class="dropdown">
          <span style="color: white;">掲示板</span>
          <div class="dropdown-content">
            <%= link_to '掲示板一覧', bulletins_path %>
            <%= link_to '掲示板作成', new_bulletin_path %>
          </div>
        </li>
        <li class="dropdown">
          <span style="color: white;">イベント</span>
          <div class="dropdown-content">
            <%= link_to 'イベント一覧', events_path %>
            <%= link_to 'イベント作成', new_event_path %>
          </div>
        </li>
        <li><%= link_to 'カレンダー', calendar_events_path %></li>
        <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
        <li>
          <span class="notification-icon">
            <%= link_to user_notifications_path do %>
              <i class="fa-solid fa-bell"></i>
            <% end %>
          </span>
        </li>
        <li>
          <% if current_user.icon_image.attached? %>
            <%= link_to edit_user_path(current_user) do %>
              <%= image_tag rails_blob_path(current_user.icon_image, only_path: true), class: "user-icon" %>
            <% end %>
          <% else %>
            <%= link_to edit_user_path(current_user) do %>
              <i class="fa-solid fa-user fa-xl"></i>
            <% end %>
          <% end %>
        </li>
      <% else %>
        <li><%= link_to 'イベント一覧', events_path %></li>
        <li><%= link_to 'ログイン', login_path %></li>
        <li><%= link_to 'ユーザー登録', new_user_path %></li>
      <% end %>
    </ul>
  </nav>
</header>