config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  post '/callback', to: 'line_webhook#callback'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get '/notifications', to: 'notifications#index', as: 'user_notifications'
  resources :users
  resources :events do
    get 'calendar', on: :collection
    resources :reservations, only: %i[new create destroy]
  end
  resources :bulletins do
    member do
      post 'like'
      delete 'unlike'
    end
  end
  resources :notifications, only: [:index] do
    member do
      put :mark_as_read
    end
  end
  resources :chat_messages, only: %i[index create]
  resources :bulletin_chats, only: %i[index create]
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user
  has_many :event_tags, dependent: :destroy
  has_many :tags, through: :event_tags
  has_many :reservations, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
end

app/controllers/events_controller.rb
# frozen_string_literal: true
require 'line/bot'
class EventsController < ApplicationController
  def index
    @q = Event.ransack(params[:q])
    @events = @q.result.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @event = Event.new
  end

  def create
    tag_names = event_params.delete(:tag_list).split(',')
    @event = current_user.events.build(event_params)

    if @event.save
      create_tags(tag_names)
      create_notification
      send_line_notification(@event)
      redirect_to events_path, notice: 'イベントが作成されました。'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    session[:user_name] = current_user.nickname
  end

  def calendar
    @events = Event.all
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: 'イベントが削除されました。'
  end

  private

  def send_line_notification(event)
    client = Line::Bot::Client.new { |config|
      config.channel_secret = ENV['LINE_CHANNEL_SECRET']
      config.channel_token = ENV['LINE_CHANNEL_TOKEN']
    }
    message = {
      type: 'text',
      text: "新しいイベントが作成されました\n
      イベント名: #{event.name}\n
      開催日時: #{event.start_time.strftime('%Y年%m月%d日 %H:%M')}\n
      リンク: #{event.link}\n"
    }
    

    # ここで友達全員に通知を送る
    client.broadcast(message)
end


  def event_params
    params.require(:event).permit(:name, :detail, :start_time, :link, :tag_list)
  end

  def create_tags(tag_names)
    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name.strip)
      @event.tags << tag
    end
  end

  def create_notification
    Notification.create(content: "#{current_user.nickname}が新しいイベントが作成されました", user: current_user)
  end
end

app/views/events/calendar.html.erb
<h1>イベントカレンダー</h1>

<%= month_calendar events: @events do |date, events| %>
  <%= date.day %>

  <% events.each do |event| %>
    <div>
      <%= link_to event.name, event_path(event), data: { turbolinks: false } %>
    </div>
  <% end %>
<% end %>

app/views/events/index.html.erb
<div class="container2">
  <h1 class="page-title">イベント一覧</h1>
  
  <!-- イベント検索フォーム -->
  <%= search_form_for @q do |f| %>
    <div class="field">
      <%= f.label :tags_name_cont, "タグ名で検索" %>
      <%= f.search_field :tags_name_cont %>
    </div>
    <%= f.submit "検索" %>
  <% end %>
  
  <% if @events.any? %>
    <ul class="event-list">
      <% @events.each do |event| %>
        <li class="event-item">
          <h2 class="event-name">イベント名:<%= event.name %></h2>
          <p class="event-detail">内容:<%= event.detail %></p>
          <p class="event-date">日時：<%= event.start_time.strftime('%Y/%m/%d %H:%M') %></p>
          <p class="event-organizer">主催者：<%= event.user.nickname %></p>
          <% event.tags.each do |tag| %>
            <p class="event-tags">タグ:<%= tag.name %></p>
          <% end %>
          <%if current_user%>
          <% if event.link.present? %>
            <p class="event-link">
              <a href="<%= event.link %>" target="_blank">イベントリンク</a>
            </p>
          <% end %>
          
          <p class="event-link">
           <% if event.user == current_user %>
              <%= link_to '削除', event_path(event), method: :delete, data: { confirm: '本当に削除しますか？' } %>
           <% end %>
          <%= link_to "詳細を見る", event_path(event), data: { turbolinks: false } %>
          <% if event.user != current_user && !event.reservations.exists?(user_id: current_user.id) %>
          <%= link_to "予約へ", new_event_reservation_path(event)%>
          <% end %>
          <% end %>
    </p>
        </li>
      <% end %>
    </ul>
    <%= paginate @events%>
  <% else %>
    <p class="no-events">現在、イベントはありません。</p>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container4">
    <h1 class="page-title">新規イベント投稿</h1>

    <%= form_with model: @event, url: events_path, class: "event-form" do |f| %>
      <div class="form-group">
        <%= f.label :name, "イベント名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :detail, "詳細" %>
        <%= f.text_area :detail, class: "form-control", rows: 4  %>
      </div>

      <div class="form-group">
        <%= f.label :start_time, "日時" %>
        <%= f.datetime_select :start_time, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :link, "リンク" %>
        <%= f.url_field :link, class: "form-control" %>
        <small class="form-text text-muted">
          イベントのオンライン会議リンク（例: Zoom、Teams）をこちらに追加してください。
        </small>
      </div>

      <div class="form-group">
        <%= f.label :tag_list, 'Tags (複数入力の際は,で区切って下さい)' %>
        <%= f.text_field :tag_list, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "投稿", class: "btn btn-primary" %>
      </div>
    <% end %>

    <%= link_to "イベント一覧に戻る", events_path, class: "back-link" %>
  </div>

app/views/events/show.html.erb
<div class="container7">
<div id="event-details" class="event-details">
  <h2 class="event-details-heading">イベント詳細</h2>
  <ul class="event-list">
    <li class="event-item">
      <h3 class="event-name">イベント名: <%= @event.name %></h3>
      <p class="event-detail">内容: <%= @event.detail %></p>
      <p class="event-date">日時: <%= @event.start_time.strftime('%Y/%m/%d %H:%M') %></p>
      <p class="event-organizer">主催者: <%= @event.user.nickname %></p>
      <% @event.tags.each do |tag| %>
        <p class="event-tags">タグ:<%= tag.name %></p>
      <% end %>

      <% if @event.link.present? %>
        <p class="event-link">
          <a href="<%= @event.link %>" target="_blank">イベントリンク</a>
        </p>
      <% end %>

     

      <div class="event-actions">
      <% if @event.user == current_user %>
      <%= link_to '削除', event_path(@event), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% end %>
    <% if @event.user != current_user && !@event.reservations.exists?(user_id: current_user.id) %>
        <%= link_to "予約へ", new_event_reservation_path(@event), class: 'reservation-button' %>
        <% end %>
      </div>
    </li>
  </ul>
</div>
</div>

<div id="chat" class="chat-container">
  <h2 class="chat-heading">チャット</h2>
  <div id="chat-messages" class="chat-messages">
    
  </div>

  </div>
  <div class="chat-input-container">
    <input type="text" id="chat-input" class="chat-input" placeholder="メッセージを入力...">
    <button id="chat-send" class="chat-send">送信</button>
  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    var user_id = '<%= current_user.id %>';
    var user_name = '<%= current_user.nickname %>';
    var chatChannel;

    function createEventChatChannel(eventId) {
      chatChannel = App.cable.subscriptions.create(
        {
          channel: "EventChatChannel",
          event_id: eventId,
          user_id: user_id,
          user_name: user_name,
        },
        {
          received: function(data) {
            
            var chatMessages = document.getElementById('chat-messages');
            var messageElement = document.createElement('div');
            messageElement.className = 'chat-message';

            var userIcon = document.createElement('i');
            userIcon.className = 'fas fa-user'; 

            var userName = document.createElement('p');
            userName.className = 'user-name';
            userName.innerText = data.user_name;

            var messageContent = document.createElement('p');
            messageContent.className = 'message-content';
            messageContent.innerText = data.content;

            messageElement.appendChild(userIcon);
            messageElement.appendChild(userName);
            messageElement.appendChild(messageContent);

            chatMessages.appendChild(messageElement);
          }
        }
      );
    }

   
    var eventId = '<%= @event.id %>';

    loadChatMessageHistory(eventId);
    createEventChatChannel(eventId);

    function loadChatMessageHistory(eventId) {
      
      $.ajax({
        url: '/chat_messages',
        method: 'GET',
        data: { event_id: eventId },
        dataType: 'json',
        success: function(data) {
          var chatMessages = document.getElementById('chat-messages');
          data.forEach(function(message) {
            var messageElement = document.createElement('div');
            messageElement.className = 'chat-message';

            var userIcon = document.createElement('i');
            userIcon.className = 'fas fa-user'; 
            var userName = document.createElement('p');
            userName.className = 'user-name';
            userName.innerText = message.user_name; 

            var messageContent = document.createElement('p');
            messageContent.className = 'message-content';
            messageContent.innerText = message.content;

            messageElement.appendChild(userIcon);
            messageElement.appendChild(userName);
            messageElement.appendChild(messageContent);

            chatMessages.appendChild(messageElement);
          });
        }
      });
    }

    document.getElementById('chat-send').addEventListener('click', function() {
     
      var input = document.getElementById('chat-input');
      var message = input.value;
      if (message.trim() !== '') {
        chatChannel.perform('speak', { content: message, user_name: user_name });
        input.value = '';
      }
    });
  });
</script>